### ISSUE TITLE
We need to publish the dist folder and add support for bower

### ISSUE THREAD

**Issue by jadrake75** [jadrake75/ng-scrolling-table#79]
To move this along we need to push the dist folder of the "built" JS and CSS and also hook this up to bower

**Comment by Xanir** [comment]
All I know about adding support for Bower is that every change requires a terminal branch of type X.Y.Z
Hopefully there is an easy way to merge change to new branches instead of doing it all by hand

**Comment by jadrake75** [comment]
did not know this.  I didn't find much out there on how to go about doing this.  Perhaps instead of merging to master, we only do so when we feel there is sufficient "functionality" or "features/defects" and instead work off a release branch (ie. it is the merge source).  Then when things look "ready" they are merged, with an incremented version + distribution files and these are what get sent to bower?

**Comment by Xanir** [comment]
Ok, looks like I was not entirely correct with my last statement. I may have been just looking at how Bower works and its expectations, one being that once something is submitted it cannot be changed and a new version number if required.
However after looking at: http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/
It appears that the version picked up my Bower is both in the bower.json and a tag on the branch.
It also mentions grunt-bump that will increment these versions for you.

So maybe this is not as much of a pain to manage as I originally thought way back when I first investigated it.

**Comment by jadrake75** [comment]
Right, but we likely don't want to be bumping versions on every check-in
would we?  Or ever issue resolved.  I would think we'd want to do it in a
blob/group of issues and defects that make sense and can be thoroughly
tested together.  Maybe I am wrong and bumping with each issue resolved
would be ok.
