### ISSUE TITLE
caption tag is removed

### ISSUE THREAD

**Issue by davidglarson** [jadrake75/ng-scrolling-table#82]
If you create a table like this using ng-scrolling-table, the caption tag is removed in the rendered HTML:
<table data-table-scrolling-table="" class="rsmGrid">
    <caption>My Table</caption>
    <colgroup>
        <col/>
        <col/>
    </colgroup>
    <thead>
    <tr>
        <th>Stuff</th>
        <th>Things</th>
    </tr>
    </thead>
    <tbody>
    <tr data-ng-repeat="junk in junkModel">
        <td>{{junk.stuff}}</td>
        <td>{{junk.things}}</td>
    </tr>
    </tbody>
</table>

Refer to this tryit: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_caption_default_css

**Comment by jadrake75** [comment]
The reason for this is we are copying just the THEAD and TBODY elements into the generated tables.  We should probably copy any elements prior to THEAD into the top table and any between or after into the table surrounding the TBODY.

**Comment by jadrake75** [comment]
THEAD, CAPTION and TFOOT are now supported
